### ISSUE TITLE
Class color in chat.

### ISSUE THREAD

**Issue by Minatbar** [ScottHamper/ChatSuey#1]
Hi, this is not a bug, my chat doesn't show classcolours of anyone, it's stock colored.. I extracted all of the addons in the folder and ticked all of them except timestamps, everything else works except the colouring the ones who talk in the chat as classcolour.? Pic below 
PS, i also have chatsuey-markdownlinks ticked asw
![wowscrnshot_092016_015759](https://cloud.githubusercontent.com/assets/22225981/18651776/1d86c360-7ed6-11e6-9254-b55b7588d031.jpg)
ell

**Comment by Minatbar** [comment]
I searched nostalrius forums and on your topic about this addon i found someones pic that shows the classcolouring worked for him, pic below, so was just wondering if i am doing something wrong.
![1434721611-wowscrnshot-061715-214309](https://cloud.githubusercontent.com/assets/22225981/18651907/0feb0d1e-7ed7-11e6-96b2-20846b6dd5b6.png)

**Comment by ScottHamper** [comment]
Hey @Minatbar ,

This feature doesn't exist in ChatSuey. The screenshot you posted suggests the person is either using a different addon, or they extended ChatSuey with their own code. ChatSuey formats timestamps differently than in the above screenshot, as well as does not support showing class colors or character levels.

Sorry to disappoint!

**Comment by Minatbar** [comment]
oh, okay thank you for fast reply :)
