### ISSUE TITLE
Legion ?

### ISSUE THREAD

**Issue by Bifidus** [ScottHamper/chatsuey#6]
Hello

I see the last patch mentioning Legion and demon hunters.
Is that addon not for vanilla anymore ?
Should i NOT upgrade it ?

**Comment by ScottHamper** [comment]
Hey @Bifidus ,

ChatSuey is still for vanilla! The reference to Demon Hunters is related to a color name you can use with the markdown links addon. For example, you could write `[Thunderfury](item:19019){demonhunter}` and you would get a purple item link. The "demonhunter" color name has always been in Chatsuey, but it used to be a green color, as that was the color originally proposed by Blizzard for Demon Hunters before Legion was released.

You can read more about how the Markdown Links addon works and see a reference of all the usable colors at [the project website](https://scott.software/chatsuey/#markdown).

I'll have to see if I can re-word the release notes to make things more clear.

**Comment by Bifidus** [comment]
Ok, thank you for your answer.
