### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by Believe82** [ScottHamper/chatsuey#7]
While trying to use Timestamps I get on logon:

"Config.lua:3:attempt to index field 'DB' (a nil value)

Can you help? 

Thanks

**Comment by ScottHamper** [comment]
Hey @Believe82 ,

I'm unable to reproduce this error, but it suggests that something in the core ChatSuey addon is not loading correctly. Here's a few questions for you:
- Does the error occur if you only have the core ChatSuey addon and the ChatSuey-Timestamps addon enabled? (everything else disabled)
- Does a fresh install of [the latest 1.2.0 release](https://github.com/ScottHamper/chatsuey/releases/download/1.2.0/ChatSuey-1.2.0.zip) make any difference? (delete all existing ChatSuey folders from your `Interface/Addons` folder before copying the fresh files over).
- Does disabling all non-ChatSuey addons cause the error to go away? (perhaps there's a funky interaction going on)

Let me know what happens for these - hopefully we can narrow down the problem and reliably reproduce it.

**Comment by Believe82** [comment]
First question was a yes, and so was the second! Issue fix with deleting it all and installing your version. Thanks!
