### ISSUE TITLE
Player name auto-complete

### ISSUE THREAD

**Issue by hedgefund** [ScottHamper/chatsuey#9]
Is it possible to implement this feature in ChatSuey, so that you can hit tab to complete people's names in chat?

**Comment by ScottHamper** [comment]
Hey @hedgefund,

It's possible, but the implementation would be ugly. There's no way to query the server for what players exist, so the addon would have to maintain its own database of players. Anytime a player is met in game, whether in chat, party, raid, etc, they would need to be added to the database. Over time, the database size would grow as more players are added. That inevitably means the addon's RAM usage will slowly increase and performance will slowly decrease.

As a result, I've been avoiding implementing any feature that would require using a local database of player info. It's a similar situation for highlighting player names with their class color in chat.
